server:
    port: 8088
    session-timeout: 30
    tomcat.max-threads: 0
    tomcat.uri-encoding: UTF-8
    servlet:
        context-path: /exam

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/firstdemo
        username: root
        password: root
    mvc:
        pathmatch:
            #Spring MVC 路径匹配策略默认为ant-path-matcher
            #而 Spring Boot 2.7.x版本的默认匹配策略是 path-pattern-matcher
            matching-strategy: ant-path-matcher

swagger:
    enabled: true

logging:
    file:
        name: E:/SpringBootLog/exam.log

